/**
 * Major cities, towns, and district / division names across Pakistan for employee forms.
 * Sorted A→Z; users can still type a value not in the list (native `<datalist>` allows free text).
 */
export const PAKISTAN_CITIES: readonly string[] = [
  "Abbottabad",
  "Aliabad",
  "Attock",
  "Astore",
  "Awaran",
  "Badin",
  "Bagh",
  "Bahawalnagar",
  "Bahawalpur",
  "Bajaur",
  "Bannu",
  "Barkhan",
  "Battagram",
  "Bhakkar",
  "Bhimber",
  "Buner",
  "Chagai",
  "Chakwal",
  "Chaman",
  "Charsadda",
  "Chiniot",
  "Chishtian",
  "Dadu",
  "Dera Allah Yar",
  "Dera Bugti",
  "Dera Ghazi Khan",
  "Dera Ismail Khan",
  "Digri",
  "Dina",
  "Duki",
  "Faisalabad",
  "Fateh Jang",
  "Ghotki",
  "Ghizer",
  "Gilgit",
  "Gojra",
  "Gujar Khan",
  "Gujranwala",
  "Gujrat",
  "Gwadar",
  "Hafizabad",
  "Hangu",
  "Haripur",
  "Harnai",
  "Hattian Bala",
  "Hub",
  "Hunza",
  "Hyderabad",
  "Islamabad",
  "Jacobabad",
  "Jafarabad",
  "Jamshoro",
  "Jhal Magsi",
  "Jhang",
  "Jhelum",
  "Kalat",
  "Kambar Shahdadkot",
  "Kandhkot",
  "Karachi",
  "Karak",
  "Kashmore",
  "Kasur",
  "Kech",
  "Khairpur",
  "Khanewal",
  "Kharan",
  "Kharian",
  "Khushab",
  "Khuzdar",
  "Khyber",
  "Killa Abdullah",
  "Killa Saifullah",
  "Kohat",
  "Kohlu",
  "Kot Addu",
  "Kotli",
  "Kurram",
  "Lahore",
  "Lakki Marwat",
  "Larkana",
  "Lasbela",
  "Layyah",
  "Lodhran",
  "Loralai",
  "Lower Chitral",
  "Lower Dir",
  "Lower Kohistan",
  "Malakand",
  "Mandi Bahauddin",
  "Mansehra",
  "Mardan",
  "Mastung",
  "Matiari",
  "Mian Channu",
  "Mianwali",
  "Mirpur",
  "Mirpur Khas",
  "Mohmand",
  "Multan",
  "Murree",
  "Musakhel",
  "Muzaffarabad",
  "Muzaffargarh",
  "Nankana Sahib",
  "Narowal",
  "Naseerabad",
  "Naushahro Feroze",
  "Nawabshah",
  "Nowshera",
  "North Waziristan",
  "Nushki",
  "Okara",
  "Orakzai",
  "Pakpattan",
  "Panjgur",
  "Peshawar",
  "Pishin",
  "Qambar Shahdadkot",
  "Quetta",
  "Rahim Yar Khan",
  "Rajanpur",
  "Rawalakot",
  "Rawalpindi",
  "Rohri",
  "Sahiwal",
  "Sanghar",
  "Sargodha",
  "Shangla",
  "Sheikhupura",
  "Sherani",
  "Shikarpur",
  "Sialkot",
  "Sibi",
  "Skardu",
  "Sohbatpur",
  "South Waziristan",
  "Sujawal",
  "Sukkur",
  "Swabi",
  "Swat",
  "Talagang",
  "Tando Adam",
  "Tando Allahyar",
  "Tando Muhammad Khan",
  "Tank",
  "Taunsa",
  "Taxila",
  "Tharparkar",
  "Thatta",
  "Timergara",
  "Toba Tek Singh",
  "Tor Ghar",
  "Umerkot",
  "Upper Chitral",
  "Upper Dir",
  "Upper Kohistan",
  "Usta Muhammad",
  "Vehari",
  "Wana",
  "Washuk",
  "Wazirabad",
  "Zhob",
  "Ziarat",
].sort((a, b) => a.localeCompare(b));
